### ISSUE TITLE
mouse stopped working.

### ISSUE THREAD

**Issue by altruios** [dille12/2dshooter#26]
button clicks no longer register in the main screen. seeing if I can isolate the change that happened that broke something :)

**Comment by altruios** [comment]
okay. super weird: I'm guessing it's on my end - and not the code at this point - going back to commits I KNOW work - and same thing... looking more into it - but now not sure where to look :/

**Comment by dille12** [comment]
I have an idea, since you have a 4k monitor, the game might calculate the mouse pos wring, check if the buttons light up when in different spots of the screen

**Comment by Velas2** [comment]
It may have been introduced with the change to app.pygame that was not thorough enough.
Please see PR: https://github.com/dille12/2dshooter/pull/27
This may resolve this issue.

**Comment by dille12** [comment]
The game worked on my friend two days ago who has a 2k monitor, did you update the app.pygame yesterday?

**Comment by Velas2** [comment]
I would have to look through commits in your repo to see when those changes came in.

The PR included changes that *should have* been made when I first introduced app.pygame - my apologies for missing those references in game.py. I'm still a bit confused as to how this mattered, I didn't see the pygame instance being passed, but pygame may be handling context maintenance externally.

Either way - my goal for introdoucing app.py / App class is to start isolating code blocks to facilitate unit testing and easier multi developer work flows. 

The general idea is to attach all objects to app, and pass app as needed and stop worrying about what items from say the RUN.py context need to carry over to say game,py.

Also, git workflow is a pain with large files - smaller files equal less collisions during commits, fewer manual merge reviews, etc.

I should be more thorough though, and will be in the future.

**Comment by altruios** [comment]
oh, I like that Velas2 - I'm all for isolating and making unit tests more viable.

**Comment by altruios** [comment]
I'll be on the discord later - would starting at run.py and working top down be the way to go?

**Comment by Velas2** [comment]
I need to get discord reinstallled.

I had started by moving existing classes out, then was targeting those now nested functions in main().

However, I was logically at the top working down.

I have some work I haven't shared yet on this, need to check it's state and get it current w/ upstream (it's close if not current)

I believe I was in the middle of changing all vars coming from get_pref...() to be app attribs in place... planning to very soon after move that line from RUN.py to App init().

I great goal IMO is to get RUN.py under 200 lines ! That's a random target and roughly 1/3 of what was in run when I started.

**Comment by altruios** [comment]
aye: under 200 for run sounds good.
from a JS background - usually it's a good idea to have one main- function/class per file - there are some instances where that might cause trouble - and I'll be looking at those places later tonight - and want to determine if that's a good idea or not.

**Comment by altruios** [comment]
testing on another (windows) computer (at lunch). it looks like the mouse and screen are now aligned... when I have python in the same window as the primary - if I do not have python in the same window as the primary: the window is displaced in the direction of the primary screen (to the window covers multiple screens, is unmovable... but the mouse is still aligned 👍  )
weird screen issues seem to be stemming from that basic idea - and I have no idea how to make that more robust - short of doing something really dumb (writing a launcher to run the python instance in the target monitor instead of the original script... )


current set up is with these monitors:
1: 2540 x 1440
2: 1680 x 1050
3: 1920 x 1200 - is_primary.


this is a new issue: but not a breaking one - so I'mma close this thread - and see if I can come up with anything when I get off work.

**Comment by Velas2** [comment]
If this behavior was introduced with the addition of app.pygame...

Then I suspect it's because pygame is somewhat initialized now within RUN... [running on python interpreter screen maybe], and the game.py or whatever actually spawns the game window [not a pygame expert] is throwing it on the "other" monitor, but now it's pre-initialized (using app.pygame) setup in RUN.

Just a hunch. 

If so, we should be working toward moving as much init stuff to app (or somewhere outside run) as possible.

I see a general structure of run - being the entry point - as being a small as possible.

Show me the general startup / run time flow / shut down. 

import other code as needed, call their inits(), etc. Ideally use external classes, etc to pass higher level structure data among other modules/classes.

So fixing this may be a matter of finding whatever in Run is doing some pygame init (and it's like 30 min away in my plans anyway) and move that to App... that may not fix it, may need to dig a bit further or put it in a func in App and call it from game.py just to see what happens

**Comment by Velas2** [comment]
PR: https://github.com/dille12/2dshooter/pull/28

implemented above (as planned anyway) and pushed all refactor I was working on wrt app.py / run.py. tested a few games myself, and ran tests.py.

**Comment by dille12** [comment]
Sorry i've been at work the whole day, so was the problem different aspect ratio? Or does the game get different monitor's resolution while opening the game into another? And I love that run.py chop down, I'll try to make game.py a lot clearer, I've got some ideas for it

**Comment by altruios** [comment]
got a branch that's starting to organize the weapons/objects into something more extensible - it's not ready, but it should help with testing once it's done.
https://github.com/altruios/2dshooter/tree/weapon_organize

**Comment by altruios** [comment]
and yeah: it was a mix-mash of ratios. but got it fixed: problem was i believe on my end and not having a primary monitor set.
