### ISSUE TITLE
Crashed while playing  [https://github.com/dille12/2dshooter/pull/29]

### ISSUE THREAD

**Issue by Velas2** [dille12/2dshooter#30]
Zombie spawned with id 2292
Zombie spawned with id 3799
Zombie spawned with id 2694
Zombie spawned with id 908
Zombie spawned with id 2981
Zombie spawned with id 3522
Zombie spawned with id 2547
Zombie spawned with id 2555
Zombie spawned with id 2949
EXPLOSION ADDED
Zombie spawned with id 1227
Zombie spawned with id 1894
Zombie spawned with id 2729
Zombie spawned with id 215
Zombie spawned with id 608
Zombie spawned with id 3177
Zombie spawned with id 3805
Zombie spawned with id 4026
Dropping: {'item': <classes.Item object at 0x000000000EA30708>, 'amount': 1}
Zombie spawned with id 42
DROP: 33.32363348513192
{33.32363348513192: ['HE Grenade', 0], 29.32363348513192: ['Heroin', 4], 28.77363348513192: ['Cocaine', 4.55], 27.773
48513192: ['Diazepam', 5.55], 25.77363348513192: ['45 ACP', 7.55], 18.77363348513192: ['50 CAL', 14.55], 15.773633485
92: ['9MM', 17.55], 9.77363348513192: ['12 GAUGE', 23.55], 6.773633485131921: ['7.62x39MM', 26.55], 3.773633485131920
['Sentry Turret', 29.55], 0.7736334851319242: ['Barricade', 32.55]}
KEY 32.55 DROP 33.32363348513192
Zombie spawned with id 794
Zombie spawned with id 591
Zombie spawned with id 1082
Zombie spawned with id 3930
Zombie spawned with id 879
STILL TO BE REMOVED: 5 STACK AMOUNT: 5
0
DELETING SLOT
Zombie spawned with id 1896
Dropping: {'item': <classes.Item object at 0x000000000EA30708>, 'amount': 1}
GRENADE INIT
STILL TO BE REMOVED: 1 STACK AMOUNT: 2
1
throwing nade
HIT
Traceback (most recent call last):
  File "RUN.py", line 558, in <module>
    main()
  File "RUN.py", line 419, in main
    s7_2 = button7_2.tick(screen, mouse_pos, mouse_single_tick, glitch)
  File "C:\python\2dshooter-contrib\button.py", line 63, in tick
    return self.action(arg) if arg != None else self.action(self.args)
  File "RUN.py", line 125, in start_sp
    app.start_sp(args)
  File "C:\python\2dshooter-contrib\app.py", line 40, in start_sp
    full_screen_mode = full_screen_mode)
  File "C:\python\2dshooter-contrib\game.py", line 1072, in main
    x.tick(screen, map_boundaries, player_pos, camera_pos, grenade_list, explosions, expl1, map, walls_filtered)
  File "C:\python\2dshooter-contrib\armory.py", line 155, in tick
    self.molotov_explode(map)
  File "C:\python\2dshooter-contrib\armory.py", line 117, in molotov_explode
    grenade_list.remove(self)
ValueError: list.remove(x): x not in list

**Comment by dille12** [comment]
fixed!
